# Generated by Django 5.2.8 on 2025-12-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
